# Generated by Django 3.1.3 on 2020-11-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='pas',
            new_name='passw',
        ),
    ]
