# Generated by Django 3.1.1 on 2020-10-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='productMy',
        ),
    ]
