# Generated by Django 3.1.2 on 2020-10-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='productMy',
        ),
    ]
