# Generated by Django 3.1.2 on 2020-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0005_contact_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_info',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout_name', models.CharField(max_length=50)),
                ('checkout_email', models.EmailField(max_length=254)),
                ('checkout_address', models.CharField(max_length=200)),
                ('checkout_zip_code', models.CharField(max_length=200)),
                ('checkout_json', models.CharField(max_length=2000)),
            ],
        ),
    ]
