# Generated by Django 3.1.2 on 2020-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0006_checkout_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_info',
            name='checkout_phone',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout_info',
            name='checkout_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='checkout_info',
            name='checkout_zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
