# Generated by Django 3.1.3 on 2020-11-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0007_auto_20201031_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_info',
            name='checkout_phone',
            field=models.IntegerField(),
        ),
    ]
