# Generated by Django 3.1.3 on 2020-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOne', '0008_auto_20201111_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField()),
                ('tracker_desc', models.CharField(max_length=500)),
                ('tracker_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
