# Generated by Django 3.1.3 on 2020-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=200)),
                ('st_email', models.CharField(max_length=200)),
                ('st_pass', models.CharField(max_length=200)),
            ],
        ),
    ]
