# Generated by Django 3.1.3 on 2020-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=200)),
                ('post_desc', models.CharField(max_length=1000)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
